name: Saludo

on: 
  push:
    branches:
      - main
      - develop

env:
  nombre: "Cristhian Alonzo"

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo desde Main
        if: github.ref == 'refs/heads/main'
        run: echo "Hola desde main, Soy ${{ env.nombre }}"

      - name: saludo desde Develop
        if: github.ref == 'refs/heads/develop'
        run: echo "Hola desde develop, Soy ${{ env.nombre }}"
